### ISSUE TITLE
Create model, controller, migration and seeder for coktails table.

### ISSUE THREAD

**Issue by samuelebruni** [samuelebruni/laravel-boolean#2]
Whoever accepts the task of completing this task, just as we were taught, will create:

- model (attention, the name of model must be entered in the singular)👈

- controller (attention, the name of controller must be entered in the singular)👈

- migration

- seeder

all linked to the "cocktails" table. 🚀

**Comment by EsterDahri1** [comment]
Perfect, i'll do it!

**Comment by EsterDahri1** [comment]
Sorry Admin, but can I create a config file to collect all my data? relating the  cocktail seeder?

**Comment by EsterDahri1** [comment]
As in this example?
<?php

namespace Database\Seeders;

use App\Models\Cocktail;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class CocktailSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $cocktails = config('cocktails');

        foreach ($cocktails as $cocktail) {
            $new_cocktail = new Cocktail();
            $new_cocktail->thumb = $cocktail['thumb'];
            $new_cocktail->name = $cocktail['name'];
            $new_cocktail->slug = $cocktail['slug'];
            $new_cocktail->price = $cocktail['price'];
            $new_cocktail->preparation = $cocktail['preparation'];
            $new_cocktail->save();
        }
    }
}
